asset/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
from __future__ import absolute_import

from django.urls import path

from asset.views import asset,idc, product, use, workenv, area
#from . import views
app_name = 'asset'

urlpatterns = [

    # Asset View
    path('asset-list/', asset.AssetListAll.as_view(), name='asset_list'),
    path('asset-add/', asset.AssetAdd.as_view(), name='asset_add'),
    path('asset-update/<uuid:pk>/', asset.AssetUpdate.as_view(), name='asset_update'),
    path('asset-all-del/', asset.AssetAllDel.as_view(), name='asset_all_del'),
    path('asset-detail/<uuid:pk>/', asset.AssetDetail.as_view(), name='asset_detail'),
    path('asset-tree/', asset.AssetZtree, name='asset_ztree'),

    # IDC View
    path('idc-list/', idc.IdcList.as_view(), name='idc_list'),
    path('idc-add/', idc.IdcAdd.as_view(), name='idc_add'),
    path('idc-update/<int:pk>/', idc.IdcUpdate.as_view(), name='idc_update'),
    path('idc-all-del/', idc.IdcDel.as_view(), name='idc_all_del'),

    # Product View
    path('product-list/', product.ProductList.as_view(), name='product_list'),
    path('product-service/<int:pk>/', product.ProductService.as_view(), name='product_service'),
    path('product-add/', product.ProductAdd.as_view(), name='product_add'),
    path('product-update/<int:pk>/', product.ProductUpdate.as_view(), name='product_update'),
    path('product-chat/<int:pk>/', product.ProductChat.as_view(), name='product_chat'),
    path('product-all-del/', product.ProductDel.as_view(), name='product_all_del'),

    # Server Use View
    path('use-list/', use.UseList.as_view(), name='use_list'),
    path('use-add/', use.UseAdd.as_view(), name='use_add'),
    path('use-update/<int:pk>/', use.UseUpdate.as_view(), name='use_update'),
    path('use-all-del/', use.UseDel.as_view(), name='use_all_del'),

    # Workenv View
    path('workenv-list/', workenv.WorkEnvList.as_view(), name='workenv_list'),
    path('workenv-add/', workenv.WorkEnvAdd.as_view(), name='workenv_add'),
    path('workenv-update/<int:pk>/', workenv.WorkEnvUpdate.as_view(), name='workenv_update'),
    path('workenv-all-del/', workenv.WorkEnvDel.as_view(), name='workenv_all_del'),

    # Area View
    path('area-list/', area.AreaList.as_view(), name='area_list'),
    path('area-add/', area.AreaAdd.as_view(), name='area_add'),
    path('area-update/<int:pk>/', area.AreaUpdate.as_view(), name='area_update'),
    path('area-all-del/', area.AreaDel.as_view(), name='area_all_del'),
]

audit/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
# by leoiceo
from __future__ import absolute_import

from django.urls import path
from jobs.views import scripts
from audit.views import loginfo, joblog
#from . import views
app_name = 'audit'

urlpatterns = [
    # Asset View
    path('login-log/', loginfo.LoginLogList.as_view(), name='login-log-list'),
    path('request-log/', loginfo.RequestLogList.as_view(), name='request-log-list'),
    path('crontab-log/', joblog.CrontadbList.as_view(), name='jobs_logs_crontab'),
    path('crontab-result/', joblog.CrontabResult.as_view(), name='jobs_crontab_result'),
    path('password-change-log/', loginfo.PasswordChangeList.as_view(), name='password_change_log'),
    path('command-log/', joblog.ExecutionList.as_view(), name='jobs_logs_command'),
    path('command-result/', joblog.ExecutionResult.as_view(), name='jobs_command_result'),

    path('scripts-log/', joblog.ScriptsList.as_view(), name='jobs_logs_scripts'),
    path('scripts-result/', joblog.ScriptsResult.as_view(), name='jobs_scripts_result'),

    path('scheduling-log/', joblog.SchedulingList.as_view(), name='jobs_logs_scheduling'),
    path('scheduling-result/', joblog.SchedulingResult.as_view(), name='jobs_scheduling_result'),

    path('files-log/', joblog.BatchFilesList.as_view(), name='jobs_logs_files'),
    path('files-result/', joblog.BatchFilesResult.as_view(), name='jobs_files_result'),
    ]

jobs/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
# by leoiceo
from __future__ import absolute_import

from django.urls import path
from jobs.views import scripts, crontab, batchscripts, batchcmd, batchfiles, orchestration, batchtask
app_name = 'jobs'

urlpatterns = [
    # Scripts View
    path('scripts-list/', scripts.ScriptsListAll.as_view(), name='scripts_list'),
    path('scripts-add/', scripts.ScriptsAdd.as_view(), name='scripts_add'),
    path('scripts-update/<uuid:pk>/', scripts.ScriptsUpdate.as_view(), name='scripts_update'),
    path('scripts-all-del/', scripts.ScriptsAllDel.as_view(), name='scripts_all_del'),
    path('scripts-diff-list/<uuid:pk>/', scripts.ScriptsDiffList.as_view(), name='scripts_diff_list'),
    path('scripts-diff/', scripts.ScriptsDiff.as_view(), name='scripts_diff'),

    path('batch-files-list/', batchfiles.BatchFiles.as_view(), name='batch_files'),
    path('batch-files-list/<str:pk>/', batchfiles.BatchFilesList.as_view(), name='batch_files_list'),
    path('batch-files-process/', batchfiles.BatchFilesProcess.as_view(), name='batch_files_process'),

    path('batch-scripts-list/', batchscripts.BatchScripts.as_view(), name='batch_scripts'),
    path('batch-scripts-taskschedule/', batchscripts.TaskScheduleApi.as_view(), name='batch_scripts_taskschedule'),
    path('batch-scripts-process/', batchscripts.BatchScriptsProcess.as_view(), name='batch_scripts_process'),


    path('crontabs-list/', crontab.CrontabsListAll.as_view(), name='crontabs_list'),
    path('crontabs-add/', crontab.CrontabsAdd.as_view(), name='crontabs_add'),
    path('crontabs-all-del/', crontab.CrontabsAllDel.as_view(), name='crontabs_all_del'),
    path('crontabs-update/<int:pk>/', crontab.CrontabsUpdate.as_view(), name='crontabs_update'),
    #
    path('intervals/', crontab.IntervalsListAll.as_view(), name='intervals_list'),
    path('intervals-add/', crontab.IntervalsAdd.as_view(), name='intervals_add'),
    path('intervals-all-del/', crontab.IntervalsAllDel.as_view(), name='intervals_all_del'),
    path('intervals-update/<int:pk>/', crontab.IntervalsUpdate.as_view(), name='intervals_update'),
    #
    path('periodictasks-list/', crontab.PeriodicTasksListAll.as_view(), name='periodictasks_list'),
    path('periodictasks-add/', crontab.PeriodicTasksAdd.as_view(), name='periodictasks_add'),
    path('periodictasks-all-del/', crontab.PeriodicTaskAllDel.as_view(), name='periodictasks_all_del'),
    path('periodictasks-update/<int:pk>/', crontab.PeriodicTasksUpdate.as_view(), name='periodictasks_update'),

    path('batch-cmd-list/', batchcmd.CmdListAll.as_view(), name='cmd_list'),
    path('batch-cmd/', batchcmd.BatchCommandExecute.as_view(), name='execution_command'),
    path('batch-cmd-result/', batchcmd.BatchExecutionResult.as_view(), name='execution_result'),
    path('batch-cmd-result-flush/', batchcmd.BatchExecutionResultFlush.as_view(), name='execution_flush'),

    path('orchestration-list/', orchestration.OrchestrationListAll.as_view(), name='orchestration_list'),
    path('orchestration-add/', orchestration.OrchestrationAdd.as_view(), name='orchestration_add'),
    path('orchestration-all-del/', orchestration.OrchestrationAllDel.as_view(), name='orchestration_all_del'),
    path('orchestration-update/<uuid:pk>/', orchestration.OrchestrationUpdate.as_view(), name='orchestration_update'),

    path('batch-task-list/', batchtask.BatchTask.as_view(), name='batch_task'),
    path('batch-task-taskschedule/', batchtask.BatchTaskApi.as_view(), name='batch_task_taskschedule'),
    path('batch-task-process/', batchtask.BatchTaskProcess.as_view(), name='batch_task_process'),

    ]

opensa/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import IndexView,CheckCode,page_not_found,server_error,permission_denied
from .api import Choice_Project
from django.conf.urls.static import static
from opensa import settings
import os
from asset.api import AssetViewSet,IdcViewSet,ServiceViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register('asset', AssetViewSet)
router.register('idc', IdcViewSet)
router.register('service', ServiceViewSet)

handler404 = page_not_found
handler500 = server_error
handler403 = permission_denied

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('choice-project/', Choice_Project.as_view(), name='choice_project'),
    path('checkcode/', CheckCode, name='checkcode'),
    path('users/', include('users.urls', namespace='users')),
    path('asset/', include('asset.urls', namespace='asset')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('audit/', include('audit.urls', namespace='audit')),
    path('api/', include(router.urls)),
]

users/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
from __future__ import absolute_import

from django.urls import path

from users.views import login, users, groups, project, permission,role,keys

app_name = 'users'

urlpatterns = [
    # Login View
    path('login/', login.UserLoginView.as_view(), name='login'),
    path('logout/', login.UserLogoutView.as_view(), name='logout'),

    # User View
    path('users-list/', users.UsersListAll.as_view(), name='users_list'),
    path('users-add/', users.UsersAdd.as_view(), name='users_add'),
    path('users-update/<int:pk>/', users.UsersUpdate.as_view(), name='users_update'),
    path('users-all-del/', users.UsersAllDel.as_view(), name='users_all_del'),
    path('users-change-password/', users.UsersChangePassword.as_view(), name='users_change_password'),
    path('users-detail/<int:pk>/', users.UsersDetail.as_view(), name='users_detail'),

    # DepartMent View
    path('groups-list/', groups.GroupsListAll.as_view(), name='groups_list'),
    path('groups-add/', groups.GroupsAdd.as_view(), name='groups_add'),
    path('groups-update/<int:pk>/', groups.GroupsUpdate.as_view(), name='groups_update'),
    path('groups-all-del/', groups.GroupsAllDel.as_view(), name='groups_all_del'),

    # Project View
    path('project-list/', project.ProjectListAll.as_view(), name='project_list'),
    path('project-add/', project.ProjectAdd.as_view(), name='project_add'),
    path('project-update/<int:pk>/', project.ProjectUpdate.as_view(), name='project_update'),
    path('project-all-del/', project.ProjectDel.as_view(), name='project_all_del'),

    # KeyManage View
    path('key-list/', keys.KeyListAll.as_view(), name='key_list'),
    path('key-add/', keys.KeyAdd.as_view(), name='key_add'),
    path('key-update/<uuid:pk>/', keys.KeyUpdate.as_view(), name='key_update'),
    path('key-all-del/', keys.KeyAllDel.as_view(), name='key_all_del'),

    # PermissionList View
    path('permission-list/', permission.PermissionListAll.as_view(), name='permission_list'),
    path('permission-add/', permission.PermissionAdd.as_view(), name='permission_add'),
    path('permission-update/<int:pk>/', permission.PermissionUpdate.as_view(), name='permission_update'),
    path('permission-all-del/', permission.PermissionAllDel.as_view(), name='permission_all_del'),

    # RoleList View
    path('role-list/', role.RoleAll.as_view(), name='role_list'),
    path('role-edit/<int:pk>/', role.RoleEdit.as_view(), name='role_edit'),
    path('role-all-del/', role.RoleAllDel.as_view(), name='role_all_del'),

]

templates/admin.html
{% load i18n %}
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">

        <ul class="nav metismenu" id="side-menu">

            {% include 'nav_li_profile.html' %}

            <li id="index">
               <a href="/"><i class="fa fa-dashboard"></i> <span class="nav-label">{% trans 'Dashboard' %}</span></a>
            </li>

            <li id="asset" class="{{ asset_active }}">
                <a href="#" ><i class="fa fa-sitemap"></i> <span class="nav-label">{% trans 'Service Manage' %}</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li class="{{ asset_list_active }}">
                        <a href="{% url 'asset:asset_list' %}">{% trans 'Server Manage' %}</a>
                    </li>
                    <li class="{{ asset_idc_active }}">
                        <a href="{% url 'asset:idc_list' %}">{% trans 'Idc Manage' %}</a>
                    </li>
                    <li class="{{ asset_product_active }}">
                        <a href="{% url 'asset:product_list' %}">{% trans 'Product Manage' %}</a>
                    </li>
                    <li class="{{ asset_use_active }}">
                        <a href="{% url 'asset:use_list' %}">{% trans 'Server Use' %}</a>
                    </li>
                    <li class="{{ asset_work_active }}">
                        <a href="{% url 'asset:workenv_list' %}">{% trans 'Work Env' %}</a>
                    </li>
                    <li class="{{ asset_area_active }}">
                        <a href="{% url 'asset:area_list' %}">{% trans 'Area Manage' %}</a>
                    </li>
                </ul>
            </li>

            <li id="jobs" class="{{ jobs_active }}">
                <a href="#"><i class="fa fa-flask"></i> <span class="nav-label">{% trans 'Jobs Manage' %}</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li class="{{ scripts_manage_active }}">
                        <a href="{% url 'jobs:scripts_list' %}">{% trans 'Scripts Manage' %}</a>
                    </li>
                    <li class="{{ scheduled_tasks_active }}">
                        <a href="{% url 'jobs:periodictasks_list' %}">{% trans 'Scheduled Tasks' %}</a>
                    </li>
                    <li class="{{ tasks_scheduling_active }}">
                        <a href="{% url 'jobs:orchestration_list' %}">{% trans 'Task scheduling' %}</a>
                    </li>
                    <li class="{{ batch_tasks_active }}">
                        <a href="#">{% trans 'Batch Tasks' %}<span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li class="{{ batch_file_active }}"><a href="{% url 'jobs:batch_files' %}">{% trans 'File Distribution' %}</a></li>
                            <li class="{{ batch_cmd_active}}"><a href="{% url 'jobs:cmd_list' %}">{% trans 'Batch CMD' %}</a></li>
                            <li class="{{ batch_script_active }}"><a href="{% url 'jobs:batch_scripts' %}">{% trans 'Batch Scripts' %}</a></li>
                            <li class="{{ batch_task_active }}"><a href="{% url 'jobs:batch_task' %}">{% trans 'Batch Tasks' %}</a></li>
                        </ul>
                    </li>
                    <li class="{{ crontab_active }}">
                        <a href="{% url 'jobs:crontabs_list' %}">{% trans 'Crontab' %}</a>
                    </li>
                    <li class="{{ interval_active }}">
                        <a href="{% url 'jobs:intervals_list' %}">{% trans 'Interval' %}</a>
                    </li>
                </ul>
            </li>

            <li id="audit" class="{{ audit_active }}">
                <a href="#"><i class="glyphicon glyphicon-eye-open"></i> <span class="nav-label">{% trans 'Audits' %}</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ audit_login_active }}"><a href="{% url 'audit:login-log-list' %}">{% trans 'Login Log' %}</a></li>
                    <li class="{{ audit_request_active }}"><a href="{% url 'audit:request-log-list' %}">{% trans 'Request Log' %}</a></li>
                    <li class="{{ jobs_logs }}"><a href="{% url 'audit:jobs_logs_command' %}">{% trans 'Jobs Log' %}</a></li>
                    <li class="{{ password_change_log }}"><a href="{% url 'audit:password_change_log' %}">{% trans 'Password Log' %}</a></li>
                </ul>
            </li>

            <li id="users" class="{{ users_active }}">
                <a href="#" ><i class="fa fa-gears"></i> <span class="nav-label">{% trans 'System Setup' %}</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li class="{{ users_users_list }}">
                        <a href="{% url 'users:users_list' %}">{% trans 'User Manage' %}</a>
                    </li>
                    <li class="{{ users_groups_list }}">
                        <a href="{% url 'users:groups_list' %}">{% trans 'DepartMent Manage' %}</a>
                    </li>
                    <li class="{{ users_project_list }}">
                        <a href="{% url 'users:project_list' %}">{% trans 'Project Manage' %}</a>
                    </li>
                    <li class="{{ users_key_list }}">
                        <a href="{% url 'users:key_list' %}">{% trans 'Key Manage' %}</a>
                    </li>
                    <li class="{{ users_role_list }}">
                        <a href="{% url 'users:role_list' %}">{% trans 'Role Manage' %}</a>
                    </li>
                    <li class="{{ users_permission_list }}">
                        <a href="{% url 'users:permission_list' %}">{% trans 'Permission List' %}</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

templates/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load i18n %}
{% block page-content %}
{% endblock %}

templates/nav.html
{% ifequal user.is_superuser 1 %}
    {% include 'admin.html' %}
{% else %}
    {% include 'nav_users.html' %}
{% endifequal %}

templates/nav_cat_bar.html
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>{{ header_title }}</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">{{nav}}</a>
            </li>
            <li>
                <a>{{ tip }}</a>
            </li>
            <li class="active">
                <strong>{{zone}}</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>


templates/nav_li_profile.html
{% load i18n %}
{% load static %}
<li class="nav-header">
    <div class="dropdown profile-element">
        <span>
            <img alt="image" class="img-circle" width="48" height="48" src="/static/img/a8.jpg" />
        </span>
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear">
                <span class="block m-t-xs">
                    <strong class="font-bold">{{ user.username }}  <span style="color: #8095a8"></span></strong>
                </span>
                <span class="text-muted text-xs block">
                     {% trans 'UserProfile' %}<b class="caret"></b>
                </span>
            </span>
        </a>
        <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li id="admin"><a href="/admin/" target="_blank">{% trans 'Backend' %}</a></li>
            <li id="manager"><a href="{% url  "users:users_detail"   pk=user.id %}">{% trans 'MyProfile' %}</a></li>
            <li id="personal"><a href="#">{% trans 'Change Password' %}</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'users:logout' %}">{% trans 'Logout' %}</a></li>
        </ul>
    </div>
    <div class="logo-element">
        JS+
    </div>
</li>

templates/nav_users.html
{% load i18n %}
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">

        <ul class="nav metismenu" id="side-menu">

            {% include 'nav_li_profile.html' %}

            <li id="index">
               <a href="/"><i class="fa fa-dashboard"></i> <span class="nav-label">{% trans 'Dashboard' %}</span></a>
            </li>

            {% for p in user.role.permission.all %}
                {% ifequal p.lable_name "asset_list" %}
                <li id="asset" class="{{ asset_active }}">
                <a href="#" ><i class="fa fa-sitemap"></i> <span class="nav-label">{% trans 'Service Manage' %}</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        {% for m in  p.menu.all %}
                            {% ifequal m.first "asset-list" %}
                                <li class="{{ asset_list_active }}">
                                    <a href="{% url 'asset:asset_list' %}">{% trans 'Server Manage' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "idc-list" %}
                                <li class="{{ asset_idc_active }}">
                                    <a href="{% url 'asset:idc_list' %}">{% trans 'Idc Manage' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "product-list" %}
                                <li class="{{ asset_product_active }}">
                                    <a href="{% url 'asset:product_list' %}">{% trans 'Product Manage' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "use-list" %}
                                <li class="{{ asset_use_active }}">
                                    <a href="{% url 'asset:use_list' %}">{% trans 'Server Use' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "workenv-list" %}
                                <li class="{{ asset_work_active }}">
                                    <a href="{% url 'asset:workenv_list' %}">{% trans 'Work Env' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "area-list" %}
                                <li class="{{ asset_area_active }}">
                                    <a href="{% url 'asset:area_list' %}">{% trans 'Area Manage' %}</a>
                                </li>
                            {% endifequal %}
                        {% endfor %}
                    </ul>
                </li>
                {% endifequal %}
            {% endfor %}

            {% for p in user.role.permission.all %}
                {% ifequal p.lable_name "jobs_list" %}
                <li id="jobs" class="{{ jobs_active }}">
                <a href="#"><i class="fa fa-flask"></i> <span class="nav-label">{% trans 'Jobs Manage' %}</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    {% for m in  p.menu.all %}
                        {% ifequal m.first "scripts-list" %}
                            <li class="{{ scripts_manage_active }}">
                                <a href="{% url 'jobs:scripts_list' %}">{% trans 'Scripts Manage' %}</a>
                            </li>
                        {% endifequal %}
                        {% ifequal m.first "periodictasks" %}
                            <li class="{{ scheduled_tasks_active }}">
                                <a href="{% url 'jobs:periodictasks_list' %}">{% trans 'Scheduled Tasks' %}</a>
                            </li>
                        {% endifequal %}
                        {% ifequal m.first "asset-list" %}
                            <li class="{{ tasks_scheduling_active }}">
                                <a href="#">{% trans 'Task scheduling' %}</a>
                            </li>
                        {% endifequal %}
                        {% ifequal m.first "crontabs" %}
                            <li class="{{ crontab_active }}">
                                <a href="{% url 'jobs:crontabs_list' %}">{% trans 'Crontab' %}</a>
                            </li>
                        {% endifequal %}
                        {% ifequal m.first "intervals" %}
                            <li class="{{ interval_active }}">
                                <a href="{% url 'jobs:intervals_list' %}">{% trans 'Interval' %}</a>
                            </li>
                        {% endifequal %}
                    {% endfor %}
                    <li class="{{ batch_tasks_active }}">
                        <a href="#">{% trans 'Batch Tasks' %}<span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            {% for m in p.menu.all %}
                                {% ifequal m.first "batch-files" %}
                                    <li class="{{ batch_file_active }}"><a href="{% url 'jobs:batch_files' %}">{% trans 'File Distribution' %}</a></li>
                                {% endifequal %}
                                {% ifequal m.first "batch-cmd" %}
                                    <li class="{{ batch_cmd_active}}"><a href="{% url 'jobs:cmd_list' %}">{% trans 'Batch CMD' %}</a></li>
                                {% endifequal %}
                                {% ifequal m.first "batch-scripts" %}
                                    <li class="{{ batch_script_active }}"><a href="{% url 'jobs:batch_scripts' %}">{% trans 'Batch Scripts' %}</a></li>
                                {% endifequal %}
                                {% ifequal m.first "batch-tasks" %}
                                    <li class="{{ batch_task_active }}"><a href="{% url 'jobs:batch_task' %}">{% trans 'Batch Tasks' %}</a></li>
                                {% endifequal %}
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                </li>
                {% endifequal %}
            {% endfor %}

            {% for p in user.role.permission.all %}
                {% ifequal p.lable_name "audit_list" %}
                    <li id="audit" class="{{ audit_active }}">
                        <a href="#"><i class="glyphicon glyphicon-eye-open"></i> <span class="nav-label">{% trans 'Audits' %}</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            {% for m in  p.menu.all %}
                                {% ifequal m.first "login-log" %}
                                    <li class="{{ audit_login_active }}"><a href="{% url 'audit:login-log-list' %}">{% trans 'Login Log' %}</a></li>
                                {% endifequal %}
                                {% ifequal m.first "request-log" %}
                                    <li class="{{ audit_request_active }}"><a href="{% url 'audit:request-log-list' %}">{% trans 'Request Log' %}</a></li>
                                {% endifequal %}
                                {% ifequal m.first "jobs-log" %}
                                    <li class="{{ jobs_logs }}"><a href="{% url 'audit:jobs_logs_command' %}">{% trans 'Jobs Log' %}</a></li>
                                {% endifequal %}
                                {% ifequal m.first "password-change-log" %}
                                    <li class="{{ password_change_log }}"><a href="{% url 'audit:password_change_log' %}">{% trans 'Password Log' %}</a></li>
                                {% endifequal %}
                            {% endfor %}
                        </ul>
                    </li>
                {% endifequal %}
            {% endfor %}

            {% for p in user.role.permission.all %}
                {% ifequal p.lable_name "users_list" %}
                <li id="users" class="{{ users_active }}">
                    <a href="#" ><i class="fa fa-gears"></i> <span class="nav-label">{% trans 'System Setup' %}</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        {% for m in  p.menu.all %}
                            {% ifequal m.first "user-manage" %}
                                <li class="{{ users_users_list }}">
                                    <a href="{% url 'users:users_list' %}">{% trans 'User Manage' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "department-manage" %}
                                <li class="{{ users_groups_list }}">
                                    <a href="{% url 'users:groups_list' %}">{% trans 'DepartMent Manage' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "project-manage" %}
                                <li class="{{ users_project_list }}">
                                    <a href="{% url 'users:project_list' %}">{% trans 'Project Manage' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "role-manage" %}
                                <li class="{{ users_role_list }}">
                                    <a href="{% url 'users:role_list' %}">{% trans 'Role Manage' %}</a>
                                </li>
                            {% endifequal %}
                            {% ifequal m.first "permission-manage" %}
                                <li class="{{ users_permission_list }}">
                                    <a href="{% url 'users:permission_list' %}">{% trans 'Permission List' %}</a>
                                </li>
                            {% endifequal %}
                        {% endfor %}
                    </ul>
                </li>
                {% endifequal %}
            {% endfor %}

        </ul>
    </div>
</nav>