jobs/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
# by leoiceo
from __future__ import absolute_import

from django.urls import path
from jobs.views import scripts, crontab, batchscripts, batchcmd, batchfiles, orchestration, batchtask
app_name = 'jobs'

urlpatterns = [
    # Scripts View
    path('scripts-list/', scripts.ScriptsListAll.as_view(), name='scripts_list'),
    path('scripts-add/', scripts.ScriptsAdd.as_view(), name='scripts_add'),
    path('scripts-update/<uuid:pk>/', scripts.ScriptsUpdate.as_view(), name='scripts_update'),
    path('scripts-all-del/', scripts.ScriptsAllDel.as_view(), name='scripts_all_del'),
    path('scripts-diff-list/<uuid:pk>/', scripts.ScriptsDiffList.as_view(), name='scripts_diff_list'),
    path('scripts-diff/', scripts.ScriptsDiff.as_view(), name='scripts_diff'),

    path('batch-files-list/', batchfiles.BatchFiles.as_view(), name='batch_files'),
    path('batch-files-list/<str:pk>/', batchfiles.BatchFilesList.as_view(), name='batch_files_list'),
    path('batch-files-process/', batchfiles.BatchFilesProcess.as_view(), name='batch_files_process'),

    path('batch-scripts-list/', batchscripts.BatchScripts.as_view(), name='batch_scripts'),
    path('batch-scripts-taskschedule/', batchscripts.TaskScheduleApi.as_view(), name='batch_scripts_taskschedule'),
    path('batch-scripts-process/', batchscripts.BatchScriptsProcess.as_view(), name='batch_scripts_process'),


    path('crontabs-list/', crontab.CrontabsListAll.as_view(), name='crontabs_list'),
    path('crontabs-add/', crontab.CrontabsAdd.as_view(), name='crontabs_add'),
    path('crontabs-all-del/', crontab.CrontabsAllDel.as_view(), name='crontabs_all_del'),
    path('crontabs-update/<int:pk>/', crontab.CrontabsUpdate.as_view(), name='crontabs_update'),
    #
    path('intervals/', crontab.IntervalsListAll.as_view(), name='intervals_list'),
    path('intervals-add/', crontab.IntervalsAdd.as_view(), name='intervals_add'),
    path('intervals-all-del/', crontab.IntervalsAllDel.as_view(), name='intervals_all_del'),
    path('intervals-update/<int:pk>/', crontab.IntervalsUpdate.as_view(), name='intervals_update'),
    #
    path('periodictasks-list/', crontab.PeriodicTasksListAll.as_view(), name='periodictasks_list'),
    path('periodictasks-add/', crontab.PeriodicTasksAdd.as_view(), name='periodictasks_add'),
    path('periodictasks-all-del/', crontab.PeriodicTaskAllDel.as_view(), name='periodictasks_all_del'),
    path('periodictasks-update/<int:pk>/', crontab.PeriodicTasksUpdate.as_view(), name='periodictasks_update'),

    path('batch-cmd-list/', batchcmd.CmdListAll.as_view(), name='cmd_list'),
    path('batch-cmd/', batchcmd.BatchCommandExecute.as_view(), name='execution_command'),
    path('batch-cmd-result/', batchcmd.BatchExecutionResult.as_view(), name='execution_result'),
    path('batch-cmd-result-flush/', batchcmd.BatchExecutionResultFlush.as_view(), name='execution_flush'),

    path('orchestration-list/', orchestration.OrchestrationListAll.as_view(), name='orchestration_list'),
    path('orchestration-add/', orchestration.OrchestrationAdd.as_view(), name='orchestration_add'),
    path('orchestration-all-del/', orchestration.OrchestrationAllDel.as_view(), name='orchestration_all_del'),
    path('orchestration-update/<uuid:pk>/', orchestration.OrchestrationUpdate.as_view(), name='orchestration_update'),

    path('batch-task-list/', batchtask.BatchTask.as_view(), name='batch_task'),
    path('batch-task-taskschedule/', batchtask.BatchTaskApi.as_view(), name='batch_task_taskschedule'),
    path('batch-task-process/', batchtask.BatchTaskProcess.as_view(), name='batch_task_process'),

    ]

opensa/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import IndexView,CheckCode,page_not_found,server_error,permission_denied
from .api import Choice_Project
from django.conf.urls.static import static
from opensa import settings
import os
from asset.api import AssetViewSet,IdcViewSet,ServiceViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register('asset', AssetViewSet)
router.register('idc', IdcViewSet)
router.register('service', ServiceViewSet)

handler404 = page_not_found
handler500 = server_error
handler403 = permission_denied

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('choice-project/', Choice_Project.as_view(), name='choice_project'),
    path('checkcode/', CheckCode, name='checkcode'),
    path('users/', include('users.urls', namespace='users')),
    path('asset/', include('asset.urls', namespace='asset')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('audit/', include('audit.urls', namespace='audit')),
    path('api/', include(router.urls)),
]

jobs/models.py
# !/usr/bin/env python
# ~*~ coding: utf-8 ~*~
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_celery_beat.models import  CrontabSchedule, PeriodicTask, IntervalSchedule
from django_celery_results.models import TaskResult
from django.core.exceptions import MultipleObjectsReturned, ValidationError
# Create your models here.
import uuid

class ScriptsManage(models.Model):
    SCRIPT_TYPE=(
        (0,"shell"),
        (1,"python"),
        (2,"bat"),
    )
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=64,unique=True,verbose_name=_("Script Name"))
    type = models.IntegerField(choices=SCRIPT_TYPE,verbose_name=_("Script Type"))
    args = models.CharField(max_length=255,null=True,blank=True,verbose_name=_("Script Args"))
    content = models.TextField(verbose_name=_("Script Content"))
    comment = models.CharField(max_length=128, blank=True, null=True, verbose_name=_('Script Comment'))
    create_date = models.DateTimeField(auto_now_add=True,null=True,blank=True,verbose_name=_("Create By"))
    create_user = models.ForeignKey(to="users.UserProfile", blank=True, null=True, on_delete=models.SET_NULL,verbose_name=_("Create User"))
    project = models.ForeignKey(to="users.Project",blank=True,null=True,on_delete=models.SET_NULL,verbose_name=_("Project Name"))
    update = models.ManyToManyField(to="UpdateConfigLog",blank=True,verbose_name=_("Update Log"))

    class Meta:
        db_table = "scriptsmanage"
        verbose_name = _("Scripts Manage")
        verbose_name_plural = _("Scripts Manage")

    def __str__(self):
        return self.name

class UpdateConfigLog(models.Model):
    id = models.UUIDField(default=uuid.uuid4,primary_key=True)
    type = models.CharField(max_length=32, null=True, blank=True, verbose_name=_("Config Type"))
    content = models.TextField(verbose_name=_("Config Histroy Content"))
    update_date = models.DateTimeField(auto_now_add=True,null=True, blank=True, verbose_name=_("Update By"))
    update_user = models.ForeignKey(to="users.UserProfile", blank=True, null=True, on_delete=models.SET_NULL,
                                    verbose_name=_("Update User"))
    class Meta:
        db_table = "updateconfiglog"
        verbose_name = _("Update Config Log")
        verbose_name_plural = _("Update Config Log")

    def __str__(self):
        return self.id

class ScheduledTasks(models.Model):
    project = models.ForeignKey(to="users.Project", blank=True, null=True,
                                on_delete=models.SET_NULL, verbose_name=_("User Project"))
    scritps = models.ForeignKey(to="ScriptsManage", blank=True, null=True,
                                on_delete=models.SET_NULL, verbose_name=_("Scritps Name"))
    scheduling = models.ForeignKey(to="TaskScheduling", blank=True, null=True,
                                on_delete=models.SET_NULL, verbose_name=_("Task Scheduling Name"))
    create_date = models.DateTimeField(blank=True, auto_now_add=True, verbose_name=_("Create By"))
    create_user = models.ForeignKey(to="users.UserProfile", blank=True, null=True,
                                on_delete=models.SET_NULL, verbose_name=_("Create User"))
    scheduled = models.ForeignKey(to="django_celery_beat.PeriodicTask", blank=True, null=True, related_name='scheduled_task',
                                on_delete=models.SET_NULL, verbose_name=_("Scheduled Name"))
    key = models.ForeignKey(to="users.KeyManage", blank=True, null=True,
                                on_delete=models.SET_NULL, verbose_name=_("Scheduled Name"))
    asset = models.ManyToManyField(to="asset.Asset", blank=True, related_name='asset_task', verbose_name=_("Asset"))


    class Meta:
        db_table = "scheduledtasks"
        verbose_name = _("Scheduled Tasks")
        verbose_name_plural = verbose_name





class TaskScheduling(models.Model):
    '''
    任务编排
    '''
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=128,blank=True,null=True,verbose_name=_("Task Name"))
    comment = models.CharField(max_length=128, blank=True, null=True, verbose_name=_('Orchestration Comment'))
    create_date = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name=_("Create By"))
    create_user = models.ForeignKey(to="users.UserProfile", blank=True, null=True, on_delete=models.SET_NULL,
                                    verbose_name=_("Create User"))
    project = models.ForeignKey(to="users.Project", blank=True, null=True, on_delete=models.SET_NULL,
                                verbose_name=_("Project Name"))
    task_scripts = models.ManyToManyField(to="TaskSchedulScripts",blank=True,verbose_name="Task Schedul Scripts")

    class Meta:
        db_table = "taskscheduling"
        verbose_name = _("Task Scheduling")
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name



class TaskSchedulScripts(models.Model):
    '''
    任务编排脚本
    '''

    TASKSCHEDULING_STATUS = (
        (0, "失败退出"),
        (1, "失败继续执行"),
        # (2, "执行后暂停"),
    )
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    level = models.IntegerField(blank=True,null=True,verbose_name="Execution order")
    status = models.IntegerField(choices=TASKSCHEDULING_STATUS,default=0,verbose_name="Execution Status")
    delaytime = models.IntegerField(blank=True,null=True,verbose_name="Delay Time Execution")
    scripts = models.ForeignKey(to="ScriptsManage", blank=True, null=True,
                                on_delete=models.SET_NULL, verbose_name=_("Scritps Name"))

    class Meta:
        db_table = "taskschedulscripts"
        verbose_name = _("Task Schedul Scripts")
        verbose_name_plural = verbose_name

jobs/views.py
from django.shortcuts import render

# Create your views here.

jobs/views/batchfiles.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
# by leoiceo
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import HttpResponse,render,HttpResponseRedirect
from django.views.generic import ListView, View, CreateView, UpdateView
from django.urls import reverse_lazy
from ..forms import ScritsManageForm
from opensa import settings
import json, datetime, uuid,subprocess,os,time
from asset.models import Asset
from jobs.models import ScriptsManage
from audit.models import JobsResults,TaskSchedule
from users.models import Project,UserProfile,KeyManage
from opensa.api import LoginPermissionRequired,mkdir
from jobs.utils import list_upload_info
from jobs.tasks import batch_files_func


class BatchFiles(LoginPermissionRequired,CreateView):

    model = ScriptsManage
    form_class = ScritsManageForm
    template_name = 'jobs/batch_files.html'
    success_url = reverse_lazy('jobs:batch_files')

    def get_context_data(self, **kwargs):

        context = {
            "jobs_active": "active",
            "batch_tasks_active": "active",
            "batch_file_active": "active",
        }

        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        upload_files = [request.FILES.get('file[%d]' % i) for i in range(0, len(request.FILES))]
        upload_dir = "{}/upload".format(settings.DATA_DIR)
        temp_dir = "{}".format(uuid.uuid4())
        try:

            for upload_file in upload_files:
                file_path = '{}/{}'.format(upload_dir,temp_dir)
                mkdir(file_path)

                with open("{}/{}".format(file_path,upload_file.name), 'wb+') as f:
                    for chunk in upload_file.chunks():
                        f.write(chunk)

                if upload_file.name.split(".")[-1] == "zip":
                    cmd = "unzip -o -O GB18030 {0}/{1} -d {0};rm -f {0}/{1}".format(file_path,upload_file.name)
                    result = subprocess.getstatusoutput(cmd)

                    if result[0]:
                        raise Exception(result[1])
            msg = temp_dir
        except Exception as e:
            msg = "{}: {}".format(_("Upload File failed"),e)

        return HttpResponse(msg)


class BatchFilesList(LoginPermissionRequired,CreateView):
    model = ScriptsManage
    form_class = ScritsManageForm
    template_name = 'jobs/batch_files_list.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        project = self.request.session["project"]
        key_list = Project.objects.get(name=project).key.all()
        asset_list = Asset.objects.filter(project__name=project, status=1)

        file_info = list_upload_info(pk)

        context = {
            "jobs_active": "active",
            "batch_tasks_active": "active",
            "batch_file_active": "active",
            "upload_id": pk,
            "key_list": key_list,
            "asset_list": asset_list,
            "file_info": file_info,
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

class BatchFilesProcess(LoginPermissionRequired,CreateView):
    model = ScriptsManage
    form_class = ScritsManageForm
    template_name = 'jobs/batch_files_process.html'

    def get_context_data(self, **kwargs):
        try:
            project = self.request.session["project"]
        except Exception as e:
            project = None

        upload_id = self.request.POST.get("upload_id")
        key_id = self.request.POST.get("key_id")
        asset_info = self.request.POST.get("asset_info")
        timeout = self.request.POST.get("timeout")
        remote_path = self.request.POST.get("remotepath")

        operator = UserProfile.objects.get(email=self.request.user).username
        project_id = Project.objects.get(name=project)
        file_info = list_upload_info(upload_id)
        key_obj = KeyManage.objects.get(id=key_id.strip('-'))
        asset_list = asset_info.split(',')
        while '' in asset_list:
            asset_list.remove('')
        asset_count = len(asset_list)

        jr_obj = JobsResults.objects.create(type=2, operator=operator, key=key_obj,project=project_id,
                                            job_name=_("File Distribution"),remote_path=remote_path)

        from celery import group
        yet = group(batch_files_func.s(jr_obj.id, upload_id, remote_path,timeout, i) for i in asset_list)()
        jobs_obj = JobsResults.objects.get(id=jr_obj.id)

        context = {
            "jobs_active": "active",
            "batch_tasks_active": "active",
            "batch_script_active": "active",
            "keymanage_obj": key_obj,
            "remote_path": remote_path,
            "jobs_obj": jobs_obj,
            "file_info": file_info,
            "asset_count": asset_count,
            "timeout": timeout,
            "yet": yet,
        }

        kwargs.update(context)
        return super().get_context_data(**kwargs)

templates/jobs/crontab-add-update.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load i18n %}
{% load static %}

{% block  title %}{% trans 'Intervals' %}{% endblock %}
{% block header-css %}

{% endblock %}
{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>{% trans 'Intervals' %}</h2>
            <ol class="breadcrumb">
                <li>
                     <a href="/">{% trans 'Home' %}</a>
                </li>
                <li>
                    <a href="{% url 'jobs:scripts_list' %}">{% trans 'Jobs Manage' %}</a>
                </li>
                <li class="active">
                    <strong>{% trans 'Intervals' %}</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">

            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>{% trans 'Intervals' %}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#" >{% trans 'Config Option 1' %}</a>
                                </li>
                                <li><a href="#" >{% trans 'Config Option 2' %}</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form enctype="multipart/form-data" method="post" class="form-horizontal" action="">
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>{% trans 'Crontab Basic Info' %}</h3>

                                {% bootstrap_field form.minute layout="horizontal" %}
                                {% bootstrap_field form.hour layout="horizontal" %}
                                {% bootstrap_field form.day_of_week layout="horizontal" %}
                                {% bootstrap_field form.day_of_month  layout="horizontal" %}
                                {% bootstrap_field form.month_of_year  layout="horizontal" %}
                                {% bootstrap_field form.timezone  layout="horizontal" %}

                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">
                                <button type="submit" class="btn btn-success" >{% trans 'confirm' %}</button>
                                <a class="btn btn-white" href="{% url "jobs:crontabs_list" %}">{% trans 'Cancel' %}</a>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}
{% block footer-js %}

{% endblock %}
{% block footer-js-ajax %}
{% endblock %}

templates/jobs/scripts-list.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load i18n %}
{% load static %}

{% block  title %}{% trans 'Scripts Manage' %}{% endblock %}

{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>{% trans 'Scripts Manage' %}</h2>
            <ol class="breadcrumb">
                <li>
                     <a href="/">{% trans 'Home' %}</a>
                </li>
                <li>
                    <a>{% trans 'Jobs Manage' %}</a>
                </li>
                <li class="active">
                    <strong>{% trans 'Scripts Manage' %}</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">

            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>{% trans 'Scripts Manage' %}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#" >{% trans 'Config Option 1' %}</a>
                                </li>
                                <li><a href="#" >{% trans 'Config Option 2' %}</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <form id="cha" class="form-horizontal" action="" method="GET">
                                {% csrf_token %}
                                <div class="pull-left"><input type="text" class="form-control" name="name" placeholder="{% trans 'Scripts Name' %}" required></div>
                                &nbsp;
                                <button class="btn btn-sm btn-primary" type="submit">{% trans 'Query' %}</button>
                                {% ifequal user.level 2 %}
                                    <a href="{% url 'jobs:scripts_add' %}" class="btn btn-sm btn-primary ">{% trans 'Append' %}</a>
                                    <a class="btn btn-sm btn-danger  asset_all_del">{% trans 'Batch Remove' %}</a>
                                {% endifequal %}

                            </form>

                            <form id="del_form_asset_all" class="form-horizontal" action="" method="post">
                                {% csrf_token %}

                                <table class="table table-striped table-bordered table-hover dataTables-asset">
                                    <thead>
                                    <tr>
                                       <th width="20">
                                            <input type="checkbox" id="CheckedAll">
                                        </th>
                                        <th>{% trans 'Script Name' %}</th>
                                        <th>{% trans 'Script type' %}</th>
                                        <th>{% trans 'Project Name' %}</th>
                                        <th>{% trans 'Create By' %}</th>
                                        <th>{% trans 'Create User' %}</th>
                                        <th>{% trans 'Action' %}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for row in scripts_list.object_list %}
                                        <tr class="gradeA" id="{{ row.id }}">
                                        <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                        <td>{{ row.name }}</td>
                                        <td>{{ row.get_type_display }}</td>
                                        <td>{{ row.project }}</td>
                                        <td>{{ row.create_date|date:"Y-m-d H:i:s" }}</td>
                                        <td>{{ row.create_user }}</td>
                                        <td class="center">
                                            {% ifequal user.level 2 %}
                                                <a class="btn btn-xs btn-info" href="{% url 'jobs:scripts_diff_list' pk=row.id %}">{% trans 'Scripts Diff' %}</a>
                                                <a class="btn btn-primary btn-xs " href="{% url 'jobs:scripts_update' pk=row.id %}">{% trans 'Update' %}</a>
                                                <a class="btn btn-danger btn-xs asset_del">{% trans 'Delete' %}</a>
                                            {% endifequal %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>
                                <div class="pull-right">
                                     <nav class="pagination">

                                        {% if scripts_list.has_previous %}
                                            <li class="long"><a href="?{{ scripts_list.previous_page_number.querystring }}">{% trans 'Home' %}</a></li>
                                        {% else %}
                                            <li><a href="{% url "jobs:scripts_list" %}?page=1">{% trans 'Home' %}</a></li>
                                        {% endif %}

                                        {% for page in scripts_list.pages %}
                                        {% if page %}
                                            {% ifequal page scripts_list.number %}
                                                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                            {% else %}
                                                 <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                            {% endifequal %}
                                        {% else %}
                                            <li class="none"><a href="">...</a></li>
                                        {% endif %}
                                        {% endfor %}

                                        {% if scripts_list.has_next %}
                                            <li class="long"><a href="?{{ scripts_list.next_page_number.querystring }}">{% trans 'Next' %}</a></li>
                                        {% endif %}
                                        <li>
                                            <a href="{% url "jobs:scripts_list" %}?page={{ scripts_list.paginator.num_pages }}">{% trans 'Trailer' %}</a>
                                        </li>
                                        <li><span style="color: #0a0a0a">{% trans 'Total' %}: &nbsp;{{ scripts_list.paginator.num_pages }} {% trans 'Page' %}</span>
                                        </li>
                                    </nav>
                                </div> <!--页码 -->
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}
{% block footer-js %}


    <script>
        $(document).on('click', '.asset_del', function () {
            var id = $(this).parent().parent().attr('id');
            swal({
                title: '{% trans 'You Are Sure To Delete' %}',
                text: '{% trans 'You Will Never Recover' %}',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: '{% trans 'confirm' %}',
                cancelButtonText:'{% trans 'cancel' %}',
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    headers: {"X-CSRFToken": '{{ csrf_token }}'},
                    url: "{% url 'jobs:scripts_all_del' %}",
                    type: 'POST',
                    data: {'nid': id},
                    success: function (data) {
                        var obj = JSON.parse(data);
                        if (obj.status) {
                            swal({title: '{% trans 'Delete' %}', text: '{% trans 'Deleted Successfully' %}', type: "success"}, function () {
                                window.location.reload();
                            })
                        } else {
                            swal('{% trans 'Delete Error' %}', '{% trans 'Delete Error' %}' + "[ " + obj.error + " ]" + '{% trans 'Error' %}', "error");
                        }
                    }
                });


            });

        });

        $(document).on('click', '.asset_all_del', function () {
            swal({
                title: '{% trans 'You Are Sure To Delete' %}',
                text: '{% trans 'You Will Never Recover' %}',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: '{% trans 'confirm' %}',
                cancelButtonText:'{% trans 'cancel' %}',
                closeOnConfirm: false
            }, function () {
                $.ajax({
                     headers: {"X-CSRFToken": '{{ csrf_token }}'},
                    url: "{% url 'jobs:scripts_all_del' %}",
                    type: 'POST',
                    data: $('#del_form_asset_all').serialize(),
                    success: function (data) {
                        var obj = JSON.parse(data);
                        if (obj.status) {
                            swal({title: '{% trans 'Delete' %}', text: '{% trans 'Deleted Successfully' %}', type: "success"}, function () {
                                window.location.reload();
                            })
                        } else {
                            swal('{% trans 'Delete Error' %}', '{% trans 'Delete Error' %}' + "[ " + obj.error + " ]" + '{% trans 'Error' %}', "error");
                        }
                    }
                });


            });
        });
    </script>

    {% endblock %}