jobs/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
# by leoiceo
from __future__ import absolute_import

from django.urls import path
from jobs.views import scripts, crontab, batchscripts, batchcmd, batchfiles, orchestration, batchtask
app_name = 'jobs'

urlpatterns = [
    # Scripts View
    path('scripts-list/', scripts.ScriptsListAll.as_view(), name='scripts_list'),
    path('scripts-add/', scripts.ScriptsAdd.as_view(), name='scripts_add'),
    path('scripts-update/<uuid:pk>/', scripts.ScriptsUpdate.as_view(), name='scripts_update'),
    path('scripts-all-del/', scripts.ScriptsAllDel.as_view(), name='scripts_all_del'),
    path('scripts-diff-list/<uuid:pk>/', scripts.ScriptsDiffList.as_view(), name='scripts_diff_list'),
    path('scripts-diff/', scripts.ScriptsDiff.as_view(), name='scripts_diff'),

    path('batch-files-list/', batchfiles.BatchFiles.as_view(), name='batch_files'),
    path('batch-files-list/<str:pk>/', batchfiles.BatchFilesList.as_view(), name='batch_files_list'),
    path('batch-files-process/', batchfiles.BatchFilesProcess.as_view(), name='batch_files_process'),

    path('batch-scripts-list/', batchscripts.BatchScripts.as_view(), name='batch_scripts'),
    path('batch-scripts-taskschedule/', batchscripts.TaskScheduleApi.as_view(), name='batch_scripts_taskschedule'),
    path('batch-scripts-process/', batchscripts.BatchScriptsProcess.as_view(), name='batch_scripts_process'),


    path('crontabs-list/', crontab.CrontabsListAll.as_view(), name='crontabs_list'),
    path('crontabs-add/', crontab.CrontabsAdd.as_view(), name='crontabs_add'),
    path('crontabs-all-del/', crontab.CrontabsAllDel.as_view(), name='crontabs_all_del'),
    path('crontabs-update/<int:pk>/', crontab.CrontabsUpdate.as_view(), name='crontabs_update'),
    #
    path('intervals/', crontab.IntervalsListAll.as_view(), name='intervals_list'),
    path('intervals-add/', crontab.IntervalsAdd.as_view(), name='intervals_add'),
    path('intervals-all-del/', crontab.IntervalsAllDel.as_view(), name='intervals_all_del'),
    path('intervals-update/<int:pk>/', crontab.IntervalsUpdate.as_view(), name='intervals_update'),
    #
    path('periodictasks-list/', crontab.PeriodicTasksListAll.as_view(), name='periodictasks_list'),
    path('periodictasks-add/', crontab.PeriodicTasksAdd.as_view(), name='periodictasks_add'),
    path('periodictasks-all-del/', crontab.PeriodicTaskAllDel.as_view(), name='periodictasks_all_del'),
    path('periodictasks-update/<int:pk>/', crontab.PeriodicTasksUpdate.as_view(), name='periodictasks_update'),

    path('batch-cmd-list/', batchcmd.CmdListAll.as_view(), name='cmd_list'),
    path('batch-cmd/', batchcmd.BatchCommandExecute.as_view(), name='execution_command'),
    path('batch-cmd-result/', batchcmd.BatchExecutionResult.as_view(), name='execution_result'),
    path('batch-cmd-result-flush/', batchcmd.BatchExecutionResultFlush.as_view(), name='execution_flush'),

    path('orchestration-list/', orchestration.OrchestrationListAll.as_view(), name='orchestration_list'),
    path('orchestration-add/', orchestration.OrchestrationAdd.as_view(), name='orchestration_add'),
    path('orchestration-all-del/', orchestration.OrchestrationAllDel.as_view(), name='orchestration_all_del'),
    path('orchestration-update/<uuid:pk>/', orchestration.OrchestrationUpdate.as_view(), name='orchestration_update'),

    path('batch-task-list/', batchtask.BatchTask.as_view(), name='batch_task'),
    path('batch-task-taskschedule/', batchtask.BatchTaskApi.as_view(), name='batch_task_taskschedule'),
    path('batch-task-process/', batchtask.BatchTaskProcess.as_view(), name='batch_task_process'),

    ]

opensa/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import IndexView,CheckCode,page_not_found,server_error,permission_denied
from .api import Choice_Project
from django.conf.urls.static import static
from opensa import settings
import os
from asset.api import AssetViewSet,IdcViewSet,ServiceViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register('asset', AssetViewSet)
router.register('idc', IdcViewSet)
router.register('service', ServiceViewSet)

handler404 = page_not_found
handler500 = server_error
handler403 = permission_denied

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('choice-project/', Choice_Project.as_view(), name='choice_project'),
    path('checkcode/', CheckCode, name='checkcode'),
    path('users/', include('users.urls', namespace='users')),
    path('asset/', include('asset.urls', namespace='asset')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('audit/', include('audit.urls', namespace='audit')),
    path('api/', include(router.urls)),
]

users/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
from __future__ import absolute_import

from django.urls import path

from users.views import login, users, groups, project, permission,role,keys

app_name = 'users'

urlpatterns = [
    # Login View
    path('login/', login.UserLoginView.as_view(), name='login'),
    path('logout/', login.UserLogoutView.as_view(), name='logout'),

    # User View
    path('users-list/', users.UsersListAll.as_view(), name='users_list'),
    path('users-add/', users.UsersAdd.as_view(), name='users_add'),
    path('users-update/<int:pk>/', users.UsersUpdate.as_view(), name='users_update'),
    path('users-all-del/', users.UsersAllDel.as_view(), name='users_all_del'),
    path('users-change-password/', users.UsersChangePassword.as_view(), name='users_change_password'),
    path('users-detail/<int:pk>/', users.UsersDetail.as_view(), name='users_detail'),

    # DepartMent View
    path('groups-list/', groups.GroupsListAll.as_view(), name='groups_list'),
    path('groups-add/', groups.GroupsAdd.as_view(), name='groups_add'),
    path('groups-update/<int:pk>/', groups.GroupsUpdate.as_view(), name='groups_update'),
    path('groups-all-del/', groups.GroupsAllDel.as_view(), name='groups_all_del'),

    # Project View
    path('project-list/', project.ProjectListAll.as_view(), name='project_list'),
    path('project-add/', project.ProjectAdd.as_view(), name='project_add'),
    path('project-update/<int:pk>/', project.ProjectUpdate.as_view(), name='project_update'),
    path('project-all-del/', project.ProjectDel.as_view(), name='project_all_del'),

    # KeyManage View
    path('key-list/', keys.KeyListAll.as_view(), name='key_list'),
    path('key-add/', keys.KeyAdd.as_view(), name='key_add'),
    path('key-update/<uuid:pk>/', keys.KeyUpdate.as_view(), name='key_update'),
    path('key-all-del/', keys.KeyAllDel.as_view(), name='key_all_del'),

    # PermissionList View
    path('permission-list/', permission.PermissionListAll.as_view(), name='permission_list'),
    path('permission-add/', permission.PermissionAdd.as_view(), name='permission_add'),
    path('permission-update/<int:pk>/', permission.PermissionUpdate.as_view(), name='permission_update'),
    path('permission-all-del/', permission.PermissionAllDel.as_view(), name='permission_all_del'),

    # RoleList View
    path('role-list/', role.RoleAll.as_view(), name='role_list'),
    path('role-edit/<int:pk>/', role.RoleEdit.as_view(), name='role_edit'),
    path('role-all-del/', role.RoleAllDel.as_view(), name='role_all_del'),

]

users/models.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
from django.utils.translation import ugettext_lazy as _
from django.db import models
import uuid


from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError(_('Users must have an email address'))

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
                                password=password,
                                username=username,
                                )
        user.level = 2
        user.is_superuser = True
        user.save(using=self._db)
        return user


class DepartMent(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name=_('DepartMent Name'))
    comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('DepartMent Comment'))

    class Meta:
        db_table = "department"
        verbose_name = _('DepartMent Manage')
        verbose_name_plural = _('DepartMent Manage')

    def __str__(self):
        return self.name

    @property
    def user_list(self):
        user_name = DepartMent.objects.get(name=self.name)
        return user_name.userprofile_set.all()

class Project(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name=_('Project Name'))
    mini_name = models.CharField(max_length=64, unique=True, blank=True, null=True, verbose_name=_('Project MiniName'))
    create_date = models.DateField(auto_now_add=True, blank=True, null=True, verbose_name=_('Create By'))
    comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Project Comment'))
    key = models.ManyToManyField(to="KeyManage",blank=True,verbose_name=_("Project Keyfile"))

    class Meta:
        db_table = "project"
        verbose_name = _('Project Manage')
        verbose_name_plural = _('Project Manage')

    def __str__(self):
        return self.name

    @property
    def user_name(self):
        return Project.objects.get(name=self.name).userprofile_set.all()

    @property
    def key_name(self):
        return Project.objects.get(name=self.name).key.all()

class KeyManage(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=32,unique=True,verbose_name=_("Key Name"))
    user = models.CharField(max_length=64,blank=True,null=True,verbose_name=_("Key User"))
    password = models.CharField(max_length=64,blank=True, null=True,verbose_name=_("Key Password"))
    private = models.TextField(verbose_name=_("Private Key"))
    public = models.TextField(verbose_name=_("Public Key"))
    create_date = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name=_('Create By'))

    class Meta:
        db_table = "keymanage"
        verbose_name = _('Key Manage')
        verbose_name_plural = _('Key Manage')

    def __str__(self):
        return self.name

    @property
    def project_name(self):
        key = KeyManage.objects.get(name=self.name)
        return key.project_set.all()


class PermissionList(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name=_('Permission Name'))
    lable_name = models.CharField(max_length=32, unique=True, blank=True,null=True,verbose_name=_('Permission Lable'))
    url = models.CharField(max_length=255, unique=True, blank=True, null=True, verbose_name=_('Permission Url'))
    menu = models.ManyToManyField(to="MenuList",blank=True,verbose_name=_("Menu Manager"))

    class Meta:
        db_table = "permissionList"
        verbose_name = _('Permission Manage')
        verbose_name_plural = _('Permission Manage')

    def __str__(self):
        return '{}({})'.format(self.name, self.url)

class MenuList(models.Model):
    name = models.CharField(max_length=32,blank=True,null=True,verbose_name="Menu Name")
    first = models.CharField(max_length=32,blank=True,null=True,verbose_name="First Menu")
    secondary = models.CharField(max_length=32,blank=True,null=True,default="Nothing",verbose_name="Secondary Menu")

    class Meta:
        db_table = "menuList"
        verbose_name = _('Menu Manage')
        verbose_name_plural = _('Menu Manage')

    def __str__(self):
        return "{}->{}".format(self.first,self.secondary)

class RoleList(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name=_('RoleName'))
    permission = models.ManyToManyField(to='PermissionList', blank=True, verbose_name=_('Permission List'))
    class Meta:
        db_table = "rolelist"
        verbose_name = _('Role Manage')
        verbose_name_plural = _('Role Manage')

    def __str__(self):
        return self.name

USER_LEVEL_TYEP = (
    (0, _('View')),
    (1, _('Exec')),
    (2, _('Delete')),
)


class UserProfile(AbstractBaseUser):
    email = models.EmailField(
        verbose_name=_('Email Address'),
        max_length=255,
        unique=True,
    )

    username = models.CharField(max_length=32, verbose_name=_("UserName"))
    token = models.CharField(max_length=128, default=None, blank=True, null=True, verbose_name=_("Token"))
    department = models.ForeignKey(to="DepartMent", blank=True, null=True, on_delete=models.SET_NULL,
                                   verbose_name=_('User Department'))
    mobile = models.CharField(max_length=32, default=None, blank=True, null=True, verbose_name=_('Mobile Phone'))
    project = models.ManyToManyField(to="Project", default=None, blank=True, verbose_name=_("User Project"))
    level = models.IntegerField(choices=USER_LEVEL_TYEP,default=0, blank=True, verbose_name=_('User Level'))
    role = models.ForeignKey(to="RoleList", null=True, blank=True, on_delete=models.SET_NULL,
                             verbose_name=_("User Role"))
    avatar = models.CharField(default="user.png", max_length=64, blank=True, verbose_name=_("User Avatar"))
    is_active = models.BooleanField(default=True, verbose_name=_('Active'))
    is_superuser = models.BooleanField(default=False, verbose_name=_('User Type'))
    limit = models.IntegerField(default=0, blank=True, verbose_name=_('Login Limit'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Create By'))
    login_date = models.DateTimeField(blank=True, null=True, verbose_name=_('Login By'))
    valid_date = models.DateTimeField(blank=True, null=True, verbose_name=_('Valid Date'))
    comment = models.CharField(max_length=128,blank=True, null=True, verbose_name=_('User Comment'))

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        db_table = "userprofile"
        verbose_name = _('User Manage')
        verbose_name_plural = _("User Manage")

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_perms(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_superuser

    objects = UserManager()

    #User = get_user_model()

templates/users/login.html
{% load static %}
{% load i18n %}
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="renderer" content="webkit">
    <link rel="shortcut icon" href="/static/img/html_logo.png" type="image/x-icon">
    <title>{% trans 'Login Page' %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}"  rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body class="gray-bg">
    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name"><img style="height:138px" src="{% static 'img/html_logo.png' %}"></h1>
            </div>
            <form class="m-t" action="{% url 'users:login' %}" role="form" method="post">{% csrf_token %}
                <div class="form-group">
                    <input type="email" class="form-control" name="username" value="" placeholder="用户名|Email" required="">
                </div>

                <div class="form-group">
                    <input type="password" class="form-control" name="password" value="" placeholder="密码|PassWord" required="">
                </div>

                <div class="form-group ">
                        <input class="pull-left" style="height:34px;" type="text" name='checkcode' placeholder="验证码"/>
                        <img onclick='ChangeCode();' id='imgCode' src='{% url 'checkcode' %}' title='{% trans 'Update Code' %}' />
                </div>

                <button type="submit" class="btn btn-primary block full-width m-b">{% trans 'Login' %}</button>

                {% if login_err %}
                <p>
                    <div class="alert alert-danger" id="login_err">
                        {{ login_err|safe }}
                    </div>
                </p>
                {% endif %}
                {% if messages %}
                <p>
                    <div class="alert alert-success" id="messages">
                        {{ messages|safe }}
                    </div>
                </p>
                {% endif %}
                </p>
            </form>
        </div>
    </div>
    <!-- Mainly scripts -->
     <script type="text/javascript">

            function ChangeCode() {
            var code = document.getElementById('imgCode');
            code.src += '?';
        }
    </script>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/users/project-list.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load i18n %}
{% load static %}
{% block header-css %}
    <link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
{% endblock %}

{% block  title %}{% trans 'Project' %}{% endblock %}



{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>{% trans 'Item InforMation' %}</h2>
            <ol class="breadcrumb">
                <li>
                     <a href="/">{% trans 'Home' %}</a>
                </li>
                <li>
                    <a href="{% url 'users:users_list' %}">{% trans 'System Setup' %}</a>
                </li>
                <li class="active">
                    <strong>{% trans 'Item InforMation' %}</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight   ">
        <div class="row">

            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>{% trans 'Item InforMation' %}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#" >{% trans 'Config Option 1' %}</a>
                                </li>
                                <li><a href="#" >{% trans 'Config Option 2' %}</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <form id="cha" class="form-horizontal" action="" method="GET">
                                {% csrf_token %}
{#                                <div class="pull-left"><input type="text" class="form-control" name="name" placeholder="{% trans 'Username' %}" required></div>#}
{#                                &nbsp;#}
{#                                <button class="btn btn-sm btn-primary" type="submit">{% trans 'Query' %}</button>#}
                                {% ifequal user.level 2 %}
                                <a href="{% url 'users:project_add' %}" class="btn btn-sm btn-primary ">{% trans 'Append' %}</a>

                                <a class="btn btn-sm btn-danger  asset_all_del">{% trans 'Batch Remove' %}</a>
                                {% endifequal %}
                            </form>
                            <form id="del_form_asset_all" class=""
                                  action="" method="post">
                                {% csrf_token %}
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                       <th width="20">
                                            <input type="checkbox" id="CheckedAll">
                                        </th>
                                        <th>{% trans 'Project Name' %}</th>
                                        <th>{% trans 'Project Short Name' %}</th>
                                        <th>{% trans 'User Name' %}</th>
                                        <th>{% trans 'Key Name' %}</th>
                                        <th>{% trans 'Create Time' %}</th>
                                        <th>{% trans 'Comment' %}</th>
                                        <th>{% trans 'Action' %}{{ error_performance }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   project_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                        <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                        <td><a href="{% url  "users:users_detail"   pk=row.id %}">{{ row.name }}</a>
                                        </td>
                                        <td>{{ row.mini_name }}</td>
                                        <td class="center">{% for i in row.user_name %}{{ i.username }} {% endfor %}</td>
                                        <td>{% for i in row.key_name %}{{ i.name }} {% endfor %}</td>
                                        <td>{{ row.create_date |date:"Y-m-d" }}</td>
                                        <td>{{ row.comment }}</td>
                                        <td class="center">
                                            {% ifequal user.level 2 %}
                                            <a class="btn btn-primary  btn-xs " href="{% url 'users:project_update' pk=row.id %}">{% trans 'Update' %}</a>
                                            <a class="btn btn-danger  btn-xs asset_del">{% trans 'Delete' %}</a>
                                            {% else %}
                                                <a class="btn btn-danger  btn-xs asset_del">{% trans 'No Permission' %}</a>
                                            {% endifequal %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}
{% block footer-js %}

    <script src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
    <script>

    $(document).ready(function(){
        $('.dataTables-example').dataTable().fnDestroy();
        $('.dataTables-example').DataTable({
            pageLength: 25,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            columnDefs : [ { targets : 0, "orderable" : false } ], "order" : [ [ 1, 'asc' ] ] ,
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }
            ]

        });

    });
    $(document).on('click', '.asset_del', function () {
            var id = $(this).parent().parent().attr('id');
            swal({
                title: '{% trans 'You Are Sure To Delete' %}',
                text: '{% trans 'You Will Never Recover' %}',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: '{% trans 'confirm' %}',
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    headers: {"X-CSRFToken": '{{ csrf_token }}'},
                    url: "{% url 'users:project_all_del' %}",
                    type: 'POST',
                    data: {'nid': id},
                    success: function (data) {
                        var obj = JSON.parse(data);
                        if (obj.status) {
                            swal({title: '{% trans 'Delete' %}', text: '{% trans 'Deleted Successfully' %}', type: "success"}, function () {
                                window.location.reload();
                            })
                        } else {
                            swal('{% trans 'Delete Error' %}', '{% trans 'Delete Error' %}' + "[ " + obj.error + " ]" + '{% trans 'Error' %}', "error");
                        }
                    }
                });


            });

        });

        $(document).on('click', '.asset_all_del', function () {
            swal({
                title: '{% trans 'You Are Sure To Delete' %}',
                text: '{% trans 'You Will Never Recover' %}',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: '{% trans 'confirm' %}',
                cancelButtonText:'{% trans 'cancel' %}',
                closeOnConfirm: false
            }, function () {
                $.ajax({
                     headers: {"X-CSRFToken": '{{ csrf_token }}'},
                    url: "{% url 'users:project_all_del' %}",
                    type: 'POST',
                    data: $('#del_form_asset_all').serialize(),
                    success: function (data) {
                        var obj = JSON.parse(data);
                        if (obj.status) {
                            swal({title: '{% trans 'Delete' %}', text: '{% trans 'Deleted Successfully' %}', type: "success"}, function () {
                                window.location.reload();
                            })
                        } else {
                            swal('{% trans 'Delete Error' %}', '{% trans 'Delete Error' %}' + "[ " + obj.error + " ]" + '{% trans 'Error' %}', "error");
                        }
                    }
                });


            });
        });

    </script>

    {% endblock %}
{% block footer-js-ajax %}
{% endblock %}