audit/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
# by leoiceo
from __future__ import absolute_import

from django.urls import path
from jobs.views import scripts
from audit.views import loginfo, joblog
#from . import views
app_name = 'audit'

urlpatterns = [
    # Asset View
    path('login-log/', loginfo.LoginLogList.as_view(), name='login-log-list'),
    path('request-log/', loginfo.RequestLogList.as_view(), name='request-log-list'),
    path('crontab-log/', joblog.CrontadbList.as_view(), name='jobs_logs_crontab'),
    path('crontab-result/', joblog.CrontabResult.as_view(), name='jobs_crontab_result'),
    path('password-change-log/', loginfo.PasswordChangeList.as_view(), name='password_change_log'),
    path('command-log/', joblog.ExecutionList.as_view(), name='jobs_logs_command'),
    path('command-result/', joblog.ExecutionResult.as_view(), name='jobs_command_result'),

    path('scripts-log/', joblog.ScriptsList.as_view(), name='jobs_logs_scripts'),
    path('scripts-result/', joblog.ScriptsResult.as_view(), name='jobs_scripts_result'),

    path('scheduling-log/', joblog.SchedulingList.as_view(), name='jobs_logs_scheduling'),
    path('scheduling-result/', joblog.SchedulingResult.as_view(), name='jobs_scheduling_result'),

    path('files-log/', joblog.BatchFilesList.as_view(), name='jobs_logs_files'),
    path('files-result/', joblog.BatchFilesResult.as_view(), name='jobs_files_result'),
    ]

jobs/urls.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
# by leoiceo
from __future__ import absolute_import

from django.urls import path
from jobs.views import scripts, crontab, batchscripts, batchcmd, batchfiles, orchestration, batchtask
app_name = 'jobs'

urlpatterns = [
    # Scripts View
    path('scripts-list/', scripts.ScriptsListAll.as_view(), name='scripts_list'),
    path('scripts-add/', scripts.ScriptsAdd.as_view(), name='scripts_add'),
    path('scripts-update/<uuid:pk>/', scripts.ScriptsUpdate.as_view(), name='scripts_update'),
    path('scripts-all-del/', scripts.ScriptsAllDel.as_view(), name='scripts_all_del'),
    path('scripts-diff-list/<uuid:pk>/', scripts.ScriptsDiffList.as_view(), name='scripts_diff_list'),
    path('scripts-diff/', scripts.ScriptsDiff.as_view(), name='scripts_diff'),

    path('batch-files-list/', batchfiles.BatchFiles.as_view(), name='batch_files'),
    path('batch-files-list/<str:pk>/', batchfiles.BatchFilesList.as_view(), name='batch_files_list'),
    path('batch-files-process/', batchfiles.BatchFilesProcess.as_view(), name='batch_files_process'),

    path('batch-scripts-list/', batchscripts.BatchScripts.as_view(), name='batch_scripts'),
    path('batch-scripts-taskschedule/', batchscripts.TaskScheduleApi.as_view(), name='batch_scripts_taskschedule'),
    path('batch-scripts-process/', batchscripts.BatchScriptsProcess.as_view(), name='batch_scripts_process'),


    path('crontabs-list/', crontab.CrontabsListAll.as_view(), name='crontabs_list'),
    path('crontabs-add/', crontab.CrontabsAdd.as_view(), name='crontabs_add'),
    path('crontabs-all-del/', crontab.CrontabsAllDel.as_view(), name='crontabs_all_del'),
    path('crontabs-update/<int:pk>/', crontab.CrontabsUpdate.as_view(), name='crontabs_update'),
    #
    path('intervals/', crontab.IntervalsListAll.as_view(), name='intervals_list'),
    path('intervals-add/', crontab.IntervalsAdd.as_view(), name='intervals_add'),
    path('intervals-all-del/', crontab.IntervalsAllDel.as_view(), name='intervals_all_del'),
    path('intervals-update/<int:pk>/', crontab.IntervalsUpdate.as_view(), name='intervals_update'),
    #
    path('periodictasks-list/', crontab.PeriodicTasksListAll.as_view(), name='periodictasks_list'),
    path('periodictasks-add/', crontab.PeriodicTasksAdd.as_view(), name='periodictasks_add'),
    path('periodictasks-all-del/', crontab.PeriodicTaskAllDel.as_view(), name='periodictasks_all_del'),
    path('periodictasks-update/<int:pk>/', crontab.PeriodicTasksUpdate.as_view(), name='periodictasks_update'),

    path('batch-cmd-list/', batchcmd.CmdListAll.as_view(), name='cmd_list'),
    path('batch-cmd/', batchcmd.BatchCommandExecute.as_view(), name='execution_command'),
    path('batch-cmd-result/', batchcmd.BatchExecutionResult.as_view(), name='execution_result'),
    path('batch-cmd-result-flush/', batchcmd.BatchExecutionResultFlush.as_view(), name='execution_flush'),

    path('orchestration-list/', orchestration.OrchestrationListAll.as_view(), name='orchestration_list'),
    path('orchestration-add/', orchestration.OrchestrationAdd.as_view(), name='orchestration_add'),
    path('orchestration-all-del/', orchestration.OrchestrationAllDel.as_view(), name='orchestration_all_del'),
    path('orchestration-update/<uuid:pk>/', orchestration.OrchestrationUpdate.as_view(), name='orchestration_update'),

    path('batch-task-list/', batchtask.BatchTask.as_view(), name='batch_task'),
    path('batch-task-taskschedule/', batchtask.BatchTaskApi.as_view(), name='batch_task_taskschedule'),
    path('batch-task-process/', batchtask.BatchTaskProcess.as_view(), name='batch_task_process'),

    ]

opensa/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import IndexView,CheckCode,page_not_found,server_error,permission_denied
from .api import Choice_Project
from django.conf.urls.static import static
from opensa import settings
import os
from asset.api import AssetViewSet,IdcViewSet,ServiceViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register('asset', AssetViewSet)
router.register('idc', IdcViewSet)
router.register('service', ServiceViewSet)

handler404 = page_not_found
handler500 = server_error
handler403 = permission_denied

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('choice-project/', Choice_Project.as_view(), name='choice_project'),
    path('checkcode/', CheckCode, name='checkcode'),
    path('users/', include('users.urls', namespace='users')),
    path('asset/', include('asset.urls', namespace='asset')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('audit/', include('audit.urls', namespace='audit')),
    path('api/', include(router.urls)),
]

audit/models.py
#!/usr/bin/env python
# ~*~ coding: utf-8 ~*~
from django.utils.translation import ugettext_lazy as _
from django.db import models
import uuid,json
from django_celery_results.models import TaskResult
# Create your models here.

LOGINTYPE = (
    (0, 'GET'),
    (1, 'POST'),
)

class RequestRecord(models.Model):
    username = models.ForeignKey(to="users.UserProfile", verbose_name=_("UserName"), blank=True, null=True,
                                 on_delete=models.SET_NULL)
    ipaddr = models.GenericIPAddressField(verbose_name=_("Client Address"))
    datetime = models.DateTimeField(auto_now_add=True, verbose_name=_("Request Date Time"))
    type = models.IntegerField(choices=LOGINTYPE, verbose_name=_("Request Type"))
    get_full_path = models.CharField(max_length=1024, blank=True, null=True, verbose_name=_("Request Full Path"))
    post_body = models.CharField(max_length=1024, blank=True, null=True, verbose_name=_("Request Post Body"))

    class Meta:
        db_table = "requestrecord"
        verbose_name = _('Request Record')
        verbose_name_plural = _('Request Record')

    def __str__(self):
        return self.username

JOBS_TYPE=(
    (0,_("Batch Cmd")),
    (1,_("Batch Scripts")),
    (2,_("File Distribution")),
    (3,_("Batch Task")),
    (4,_("Crontab Task")),
)
class JobsResults(models.Model):

    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    type = models.IntegerField(choices=JOBS_TYPE, blank=True, null=True, verbose_name=_("Jobs Type"))
    start_time = models.DateTimeField(auto_now_add=True, verbose_name=_("Start Time"))
    job_name = models.CharField(max_length=128,blank=True, null=True, verbose_name=_("Job Name"))
    remote_path = models.CharField(max_length=128, blank=True, null=True, verbose_name=_("Remote Path"))
    operator = models.CharField(max_length=64,null=True, blank=True, verbose_name=_('Operator'))
    key = models.ForeignKey(to="users.KeyManage",blank=True,null=True, verbose_name=_('Jobs Exec Key'),on_delete=models.SET_NULL)
    task_schedule = models.ManyToManyField(to='TaskSchedule',blank=True, verbose_name=_("Jobs Schedule"))
    project = models.ForeignKey(to="users.Project", null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_("Jobs Project"))

    class Meta:
        db_table = "jobsresults"
        verbose_name = _("Jobs Results")
        verbose_name_plural = _("Jobs Results")

    def __str__(self):
        return self.id

class TaskSchedule(models.Model):
    id = models.UUIDField(default=uuid.uuid4,primary_key=True)
    task_id = models.UUIDField(max_length=255, blank=True, null=True, verbose_name=_('Task ID'), unique=True)
    log = models.CharField(max_length=128,blank=True,null=True,verbose_name=_("Log Info"))
    #result = models.TextField(blank=True,null=True,verbose_name=_("Task Result"))
    start_time = models.DateTimeField(auto_now_add=True, verbose_name=_("Start Time"))
    total_time = models.FloatField(blank=True, null=True,verbose_name=_("Total Time"))
    asset = models.ForeignKey(to="asset.Asset", blank=True, null=True, on_delete=models.SET_NULL,
                                verbose_name=_("Tasks Asset"))

    @property
    def status(self):
        status = TaskResult.objects.get(task_id=self.task_id).status
        return status

    @property
    def result(self):
        result = TaskResult.objects.get(task_id=self.task_id).result
        return result

    @property
    def plan(self):
        try:
            current = TaskResult.objects.get(task_id=self.task_id).result
            jsons = json.loads(current)
            plan = jsons['current']
        except Exception as e:
            plan = ''
        return plan

    @property
    def operator(self):
        current = TaskSchedule.objects.get(task_id=self.task_id).jobsresults_set.all()
        return current


    class Meta:
        db_table = "taskschedule"
        verbose_name = _("Task Schedule Table")
        verbose_name_plural = _("Task Schedule Table")

    def __str__(self):
        return self.id

class PasswordChangeLog(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    user = models.CharField(max_length=128, verbose_name=_('User'))
    change_by = models.CharField(max_length=128, verbose_name=_("Change by"))
    remote_addr = models.CharField(max_length=15, verbose_name=_("Remote addr"), blank=True, null=True)
    datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "passwordchangelog"
        verbose_name = _("Password Change Log")
        verbose_name_plural = _("Password Change Log")

    def __str__(self):
        return "{} change {}'s password".format(self.change_by, self.user)

audit/views.py
from django.shortcuts import render

# Create your views here.

templates/audit/jobs_logs_command.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load i18n %}
{% load static %}

{% block  title %}{% trans 'Command Logs' %}{% endblock %}
{% block header-css %}
    <link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
{% endblock %}

{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>{% trans 'Command Logs' %}</h2>
            <ol class="breadcrumb">
                <li>
                     <a href="/">{% trans 'Home' %}</a>
                </li>
                <li>
                    <a href="{% url 'audit:login-log-list' %}">{% trans 'Audits' %}</a>
                </li>
                <li class="active">
                    <strong>{% trans 'Command Logs' %}</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12" id="split-right">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="{% url 'audit:jobs_logs_command' %}"><i class="fa fa-briefcase"></i> {% trans 'Batch Cmd Logs' %}</a></li>
                        <li class=""><a href="{% url 'audit:jobs_logs_scripts' %}"><i class="fa fa-briefcase"></i> {% trans 'Batch Scripts Logs' %}</a></li>
                        <li class=""><a href="{% url 'audit:jobs_logs_files' %}"><i class="fa fa-briefcase"></i> {% trans 'File Distribution Logs' %}</a></li>
                        <li class=""><a href="{% url 'audit:jobs_logs_scheduling' %}"><i class="fa fa-briefcase"></i> {% trans 'Batch Task Logs' %}</a></li>
                        <li class=""><a href="{% url 'audit:jobs_logs_crontab' %}">{% trans 'Crontab Task Logs' %}</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">
                                <div class="col-lg-6" style="padding-left:0px">
                                    <form id="date_form">
                                        {% csrf_token %}
                                        <div class="pull-left"><input type="text" class="form-control" name="name" placeholder="{% trans 'User Name' %}"> </div>
                                        <div class="input-group col-lg-offset-3">
                                            <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                                            <input type="text" name="date_from" class="form-control" placeholder={% trans 'Select Start Date' %} id="datetimepicker1">
                                            <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                                            <input type="text" name="date_to" class="form-control" placeholder={% trans 'Select End Date' %} id="datetimepicker2">
                                        </div>
                                    </form>
                                </div>
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-primary" form="date_form">{% trans 'Query' %}</button>
                                </div>

                                <form id="del_form_asset_all" class="form-horizontal" action="" method="post">
                                    {% csrf_token %}
                                    <table class="table table-striped table-bordered table-hover dataTables-asset">
                                        <thead>
                                        <tr>
                                            <th>{% trans 'Number' %}</th>
                                            <th>{% trans 'User Name' %}</th>
                                            <th>{% trans 'Command' %}</th>
                                            <th>{% trans 'DateTime' %}</th>
                                            <th>{% trans 'Request Meta' %}</th>
                                            <th>{% trans 'View Results' %}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for row in loginlog_list.object_list %}
                                            <tr class="gradeA" id="{{ row.id }}">
                                            <td>{{forloop.counter}}</td>
                                            <td>{{ row.operator }}</td>
                                            <td>{{ row.job_name }}</td>
                                            <td>{{ row.start_time|date:"Y-m-d H:i:s" }}</td>
                                            <td>{{ row.get_type_display }}</td>
                                            <td><a>{% trans 'View' %}</a></td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>

                                    </table>
                                    <div class="pull-right">
                                        <nav class="pagination">
                                            {% if loginlog_list.has_previous %}
                                                <li class="long"><a href="?{{ loginlog_list.previous_page_number.querystring }}">{% trans 'Home' %}</a></li>
                                            {% else %}
                                                <li><a href="{% url "audit:jobs_logs_command" %}?page=1">{% trans 'Home' %}</a></li>
                                            {% endif %}

                                            {% for page in loginlog_list.pages %}
                                                {% if page %}
                                                    {% ifequal page loginlog_list.number %}
                                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                                    {% else %}
                                                         <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                                    {% endifequal %}
                                                {% else %}
                                                    <li class="none"><a href="">...</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if loginlog_list.has_next %}
                                                <li class="long"><a href="?{{ loginlog_list.next_page_number.querystring }}">{% trans 'Next' %}</a></li>
                                            {% endif %}
                                            <li>
                                                <a href="{% url "audit:jobs_logs_command" %}?page={{ loginlog_list.paginator.num_pages }}">{% trans 'Trailer' %}</a>
                                            </li>
                                                <li><span style="color: #0a0a0a">{% trans 'Total' %}: &nbsp;{{ loginlog_list.paginator.num_pages }} {% trans 'Page' %}</span>
                                            </li>
                                        </nav>
                                    </div> <!--页码 -->
                                </form>
                            </div>
                        </div>

                    </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block footer-js %}
    <script>
    $('.gradeA').click(function () {
        var ids = $(this).attr('id');
        $.ajax({
            headers: {"X-CSRFToken": '{{ csrf_token }}'},
            url: "{% url 'audit:jobs_command_result' %}",
            type: 'POST',
            data: {'id': ids},
            success: function (data) {
                location.href= "{% url 'audit:jobs_command_result' %}"+"?id="+ids;
            }
        });
    })


    </script>
    <script>
        $('#datetimepicker1').datetimepicker({
                onGenerate:function( ct ){
                $(this).find('.xdsoft_date.xdsoft_weekend')
                //      .addClass('xdsoft_disabled');
        },
        weekends:['01.01.2014','02.01.2014','03.01.2014','04.01.2014','05.01.2014','06.01.2014'],
        yearOffset:0,
        lang:'ch',      //中文显示
        timepicker:false,
        format:'Y-m-d',         //格式年月日
        formatDate:'Y-m-d',
    });

    $('#datetimepicker2').datetimepicker({
                onGenerate:function( ct ){
                $(this).find('.xdsoft_date.xdsoft_weekend')
                //      .addClass('xdsoft_disabled');
        },
        weekends:['01.01.2014','02.01.2014','03.01.2014','04.01.2014','05.01.2014','06.01.2014'],
        yearOffset:0,
        lang:'ch',      //中文显示
        timepicker:false,
        format:'Y-m-d',         //格式年月日
        formatDate:'Y-m-d',
    });
    </script>

    {% endblock %}
    {% block footer-js-ajax %}
    {% endblock %}

templates/audit/jobs_logs_crontab.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load i18n %}
{% load static %}

{% block  title %}{% trans 'Crontab Logs Scripts' %}{% endblock %}
{% block header-css %}
    <link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
{% endblock %}

{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>{% trans 'Crontab Logs Scripts' %}</h2>
            <ol class="breadcrumb">
                <li>
                     <a href="/">{% trans 'Home' %}</a>
                </li>
                <li>
                    <a href="{% url 'audit:login-log-list' %}">{% trans 'Audits' %}</a>
                </li>
                <li class="active">
                    <strong>{% trans 'Crontab Logs Scripts' %}</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12" id="split-right">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class=""><a href="{% url 'audit:jobs_logs_command' %}"><i class="fa fa-briefcase"></i> {% trans 'Batch Cmd Logs' %}</a></li>
                        <li class=""><a href="{% url 'audit:jobs_logs_scripts' %}"><i class="fa fa-briefcase"></i> {% trans 'Batch Scripts Logs' %}</a></li>
                        <li class=""><a href="{% url 'audit:jobs_logs_files' %}"><i class="fa fa-briefcase"></i> {% trans 'File Distribution Logs' %}</a></li>
                        <li class=""><a href="{% url 'audit:jobs_logs_scheduling' %}"><i class="fa fa-briefcase"></i> {% trans 'Batch Task Logs' %}</a></li>
                        <li class="active"><a href="{% url 'audit:jobs_logs_crontab' %}">{% trans 'Crontab Task Logs' %}</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">
                                <div class="col-lg-6" style="padding-left:0px">
                                    <form id="date_form">
                                        {% csrf_token %}
                                        <div class="pull-left"><input type="text" class="form-control" name="name" placeholder="{% trans 'User Name' %}"> </div>
                                        <div class="input-group col-lg-offset-3">
                                            <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                                            <input type="text" name="date_from" class="form-control" placeholder={% trans 'Select Start Date' %} id="datetimepicker1">
                                            <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                                            <input type="text" name="date_to" class="form-control" placeholder={% trans 'Select End Date' %} id="datetimepicker2">
                                        </div>
                                    </form>
                                </div>
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-primary" form="date_form">{% trans 'Query' %}</button>
                                </div>

                                <form id="del_form_asset_all" class="form-horizontal" action="" method="post">
                                    {% csrf_token %}
                                    <table class="table table-striped table-bordered table-hover dataTables-asset">
                                        <thead>
                                        <tr>
                                            <th>{% trans 'Number' %}</th>
                                            <th>{% trans 'User Name' %}</th>
                                            <th>{% trans 'Name' %}</th>
                                            <th>{% trans 'DateTime' %}</th>
                                            <th>{% trans 'Request Meta' %}</th>
                                            <th>{% trans 'View Results' %}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for row in loginlog_list.object_list %}
                                            <tr class="gradeA" id="{{ row.id }}">
                                            <td>{{forloop.counter}}</td>
                                            <td>{{ row.operator }}</td>
                                            <td>{{ row.job_name }}</td>
                                            <td>{{ row.start_time|date:"Y-m-d H:i:s" }}</td>
                                            <td>{{ row.get_type_display }}</td>
                                            <td><a>{% trans 'View' %}</a></td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>

                                    </table>
                                    <div class="pull-right">
                                        <nav class="pagination">
                                            {% if loginlog_list.has_previous %}
                                                <li class="long"><a href="?{{ loginlog_list.previous_page_number.querystring }}">{% trans 'Home' %}</a></li>
                                            {% else %}
                                                <li><a href="{% url "audit:jobs_logs_crontab" %}?page=1">{% trans 'Home' %}</a></li>
                                            {% endif %}

                                            {% for page in loginlog_list.pages %}
                                                {% if page %}
                                                    {% ifequal page loginlog_list.number %}
                                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                                    {% else %}
                                                         <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                                    {% endifequal %}
                                                {% else %}
                                                    <li class="none"><a href="">...</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if loginlog_list.has_next %}
                                                <li class="long"><a href="?{{ loginlog_list.next_page_number.querystring }}">{% trans 'Next' %}</a></li>
                                            {% endif %}
                                            <li>
                                                <a href="{% url "audit:jobs_logs_crontab" %}?page={{ loginlog_list.paginator.num_pages }}">{% trans 'Trailer' %}</a>
                                            </li>
                                                <li><span style="color: #0a0a0a">{% trans 'Total' %}: &nbsp;{{ loginlog_list.paginator.num_pages }} {% trans 'Page' %}</span>
                                            </li>
                                        </nav>
                                    </div> <!--页码 -->
                                </form>
                            </div>
                        </div>

                    </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block footer-js %}
    <script>
    $('.gradeA').click(function () {
        var ids = $(this).attr('id');
        $.ajax({
            headers: {"X-CSRFToken": '{{ csrf_token }}'},
            url: "{% url 'audit:jobs_crontab_result' %}",
            type: 'POST',
            data: {'id': ids},
            success: function (data) {
                location.href= "{% url 'audit:jobs_crontab_result' %}"+"?id="+ids;
            }
        });
    })


    </script>
    <script>
        $('#datetimepicker1').datetimepicker({
                onGenerate:function( ct ){
                $(this).find('.xdsoft_date.xdsoft_weekend')
                //      .addClass('xdsoft_disabled');
        },
        weekends:['01.01.2014','02.01.2014','03.01.2014','04.01.2014','05.01.2014','06.01.2014'],
        yearOffset:0,
        lang:'ch',      //中文显示
        timepicker:false,
        format:'Y-m-d',         //格式年月日
        formatDate:'Y-m-d',
    });

    $('#datetimepicker2').datetimepicker({
                onGenerate:function( ct ){
                $(this).find('.xdsoft_date.xdsoft_weekend')
                //      .addClass('xdsoft_disabled');
        },
        weekends:['01.01.2014','02.01.2014','03.01.2014','04.01.2014','05.01.2014','06.01.2014'],
        yearOffset:0,
        lang:'ch',      //中文显示
        timepicker:false,
        format:'Y-m-d',         //格式年月日
        formatDate:'Y-m-d',
    });
    </script>

    {% endblock %}
    {% block footer-js-ajax %}
    {% endblock %}